#data
dataset: nuscenes
#cg3: /workspace/data/tracking/nuscenes/
#cg1: /workspace/data/tracking/train_datasets/nuscenes/
path: /workspace/data/nuscenes/
version: v1.0-trainval
category_name: all #[pedestrian, car, bicycle, truck, all]
search_bb_scale: 1.25
search_bb_offset: 2
model_bb_scale: 1.25
model_bb_offset: 0
template_size: 512
search_size: 1024
random_sample: False
sample_per_epoch: -1
degrees: True # use degrees or radians
box_aware: True
num_candidates: 4
up_axis: [0, 0, 1]
preload_offset: 10
key_frame_only: True
train_split: train_track
val_split: val
test_split: val
min_points: 1 # #
box_seven_param: True
use_z_offset: True  #  the offset to obtain sample box
limit_box_abs: True  # when generating sample box, make sure the motion is not so large.


#model configuration
net_model: OPT
use_bev: False
use_voxel_rpn: True
use_fps: True
normalize_xyz: False
feature_channel: 256 #the output channel of backbone
hidden_channel: 256 #the hidden channel of xcorr
out_channel: 32 #the output channel of xcorr
vote_channel: 256 #the channel for vote aggregation
num_proposal: 64
bc_channel: 9
k: 4
use_search_bc: False
use_search_feature: False
input_channel: 3
conv1_kernel_size: 5 # ! nuscene：5； kitti: 3
num_sampled_points: 512


# augmentation
use_augment: False
world_flip_axis: ['x']
world_rot_angle: [-0.3925, 0.3925] # i.e. [-pi/8, pi/8]
local_scale_range: [0.95, 1.05]

# re-weight
re_weight: False
lrbl: 1.0
num_f: 5
epochb: 20
lambdap: 70
lambda_decay_rate: 0.3
lambda_decay_epoch: 5
min_lambda_times: 0.01
decay_pow: 2
presave_ratio: 0.9
rw_warmup: 0

# sparse conv
sparse_quantize: True
use_feat_norm: False
base_scale: 0.1
num_levels: 2
num_knn: 8
sparse_voxel_size: [0.02, 0.02, 0.02]

# voxelization of rpn
voxel_size: [0.3, 0.3, 0.3]
xy_size: [0.3, 0.3]
area_extents: [-5.6, 5.6, -3.6, 3.6, -2.4, 2.4]
xy_area_extents: [-5.6, 5.6, -3.6, 3.6]
downsample: 1.0
regress_radius: 2

#loss configuration
objectiveness_weight: 1.5
box_weight: 0.2
vote_weight: 1.0

seg_weight: 0.2
bc_weight: 0
hm_weight: 1.0
loc_weight: 1.0
z_weight: 2.0

# testing config
reference_BB: previous_result
shape_aggregation: firstandprevious
use_z: True
limit_box: True  # pedestrian, truck, bus, car: false
IoU_space: 3

#training
batch_size: 50 #batch_size per gpu
workers: 10
epoch: 60
from_epoch: 0
lr: 0.001
optimizer: Adam  # sam
lr_decay_step: 10
lr_decay_rate: 0.1
wd: 0
checkpoint_pretrained: None
betas: [0.9, 0.999]